[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = ["alembic/versions"]

[tool.ruff.lint]
# enable rulesets
select = [
  "E", "F", "I",  # pycodestyle, pyflakes, isort
  "UP",           # pyupgrade
  "B",            # bugbear
  "SIM",          # simplify
]
ignore = [
  "B008",         # FastAPI dependency injection as default args is fine
]

[tool.ruff.lint.isort]
known-first-party = ["app", "scripts"]
combine-as-imports = true
force-single-line = false
